### ISSUE TITLE
PID generator integrated

### ISSUE THREAD

**Issue by AnotherHat** [E-Sh4rk/PokeGlitzer#2]
Hey, I don't know if you are still working on this project but I just wrote a simple extra tab to generate personality values with desired nature/ability/gender/shiny 
I'll attach a screenshot and the code of the generator function, feel free to implement it your own way if you wish so.
Wish you good luck buddy!
![image](https://user-images.githubusercontent.com/108604136/177118982-788c242b-eabf-489e-bbd9-0282e4a240dd.png)
[GeneratePID.txt](https://github.com/E-Sh4rk/PokeGlitzer/files/9037955/GeneratePID.txt)

**Comment by E-Sh4rk** [comment]
Hey!

> I don't know if you are still working on this project

Sometimes I am, when I have an idea of something to implement!

> but I just wrote a simple extra tab to generate personality values with desired nature/ability/gender/shiny

That seems great! I will definitively add this function in a next version :)
Thanks for your contribution!

**Comment by E-Sh4rk** [comment]
Implemented in afb19934431662b77c02876f95c07f58fe637d5d
