### ISSUE TITLE
[Enhancement] Import/Export Pokemon as Files

### ISSUE THREAD

**Issue by ColdStoneSys** [E-Sh4rk/PokeGlitzer#3]
It'd be a great addition to add support for .pk3 files to quickly take a look at pokemon without needing to drop them into PKHeX first then view them in PokeGlitzer. 

Thinking this option could go in the menu for when you right click on a tile.

**Comment by E-Sh4rk** [comment]
Thanks, that's definitely a good idea. Will do that when I find some time!

**Comment by E-Sh4rk** [comment]
Implemented in release 1.3.3 (04b6d33)
