### ISSUE TITLE
Conflicting Shininess/PID issue

### ISSUE THREAD

**Issue by Hextual** [E-Sh4rk/PokeGlitzer#4]
I am using your application to generate hexadecimal values to gen pokémon using gen 3 ACE - I've found legitimate PID's for the pokémon I'm genning, that matches tid/sid for shininess, but applying the shininess modifies the PID input completely, so when saving and closing it reverts from shiny to default sprite. Not sure if intended or not but here you go ;) Very useful program, thanks!
https://gyazo.com/cd5888123c04171180b203cef751356e

**Comment by E-Sh4rk** [comment]
Hello! Thank you for the compliments!

If you have found a legitimate shiny PID, why do you need to modify the Shiny checkbox?
You should only modify a field in the "PID" tab if you do not directly set the PID manually.
If you manually set a shiny PID (together with the OTID field), then the Shiny checkbox should be checked automatically, you don't need to touch it.

The OTID field should be `0xSSSSTTTT` with `SSSS` your SID written in hexadecimal and `TTTT` your TID written in hexadecimal. Or if you prefer decimal, it is `65536*SID + TID`.

**Comment by Hextual** [comment]
> Hello! Thank you for the compliments!
> 
> If you have found a legitimate shiny PID, why do you need to modify the Shiny checkbox? You should only modify a field in the "PID" tab if you do not directly set the PID manually. If you manually set a shiny PID (together with the OTID field), then the Shiny checkbox should be checked automatically, you don't need to touch it.
> 
> The OTID field should be `0xSSSSTTTT` with `SSSS` your SID written in hexadecimal and `TTTT` your TID written in hexadecimal. Or if you prefer decimal, it is `65536*SID + TID`.

I wasn’t aware SID should be used in the OTID field, I’ll mess around more with it tomorrow, thanks for clarifying my issue 👍🏻😎 GOAT
Maybe you can add an error message if only 2/4 bytes are written, on your next release 🤩 or add some tooltips showing examples, when hovering over an input field 🤘🏻

**Comment by E-Sh4rk** [comment]
Yes the terminology is not very clear, the Original Trainer ID field contains both the SID and TID of the original trainer.
It is called this way on the Pokemon Data Structure page of Bulbapedia, but in other contexts the TID only refers to the visible part of the ID...

I will add some warnings or tooltip, thanks for the suggestions!
